export const cartActionTypes = {
  TOGGLE_CART_DISPLAY: 'TOGGLE_CART_DISPLAY',
  ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
  REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
  DECREASE_ITEM_QUANTITY_FROM_CART: 'DECREASE_ITEM_QUANTITY_FROM_CART',
};
